### ISSUE TITLE
Zoom for card browser?

### ISSUE THREAD

**Issue by gajewsk2** [ospalh/anki-addons#100] opened 2017-01-24 05:15 UTC
The Browser window that allows you to search anki cards doesn't seem to be supported by Zoom. The text is extremely small for the rows and search bar. Any way to use this feature on the card browser?

**Comment by ankitest** [comment] 2017-01-24 06:31
You can try to customize fonts in Browser areas with addon [' Editor fontsize](https://ankiweb.net/shared/info/1931469441)

**Comment by gajewsk2** [comment] 2017-01-24 08:26
Ahh, very nice. Any idea how to resize the searchEdit form? Seems onBrowserSearch has access to the form, but I'm not sure how to make the height larger to work with a bigger font size.

**Comment by ospalh** [comment] 2017-01-24 08:45
Duplicate of #59

**Closed by ospalh** 2017-01-24 08:45 UTC
